from api.settings import env

RABBITMQ_BROKER_HOST = env.str("RABBITMQ_BROKER_HOST", default="")
RABBITMQ_BROKER_PORT = env.int("RABBITMQ_BROKER_PORT", default=0)
RABBITMQ_BROKER_USERNAME = env.str("RABBITMQ_BROKER_USERNAME", default="")
RABBITMQ_BROKER_PASSWORD = env.str("RABBITMQ_BROKER_PASSWORD", default="")
