# Generated by Django 5.0.2 on 2024-02-29 12:24

import core.models.fields
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted', models.DateTimeField(null=True)),
                ('deleter_id', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(default='', max_length=20)),
                ('updater_id', models.CharField(default='', max_length=20)),
                ('id', core.models.fields.ShortIdField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=11, max_length=20, prefix='C', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('team_id', models.CharField(db_index=True, max_length=20)),
                ('is_im', models.BooleanField(default=False)),
                ('is_mpim', models.BooleanField(default=False)),
                ('is_channel', models.BooleanField(default=True)),
                ('is_general', models.BooleanField(default=False)),
                ('is_random', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_read_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(default='', max_length=20)),
                ('updater_id', models.CharField(default='', max_length=20)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'channel_members',
            },
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('team_id'), name='unique_channel_name'),
        ),
        migrations.AddField(
            model_name='channelmember',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmember',
            unique_together={('channel_id', 'user_id')},
        ),
    ]
