# Generated by Django 5.0.2 on 2024-02-29 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted', models.DateTimeField(null=True)),
                ('deleter_id', models.CharField(default='', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(default='', max_length=20)),
                ('updater_id', models.CharField(default='', max_length=20)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('channel_id', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('message', 'Message')], default='message', max_length=40)),
                ('subtype', models.CharField(choices=[('', 'Empty'), ('message_changed', 'Message Changed'), ('message_replied', 'Message Replied'), ('channel_joined', 'Channel Joined'), ('bot_message', 'Bot Message')], default='', max_length=40)),
                ('text', models.TextField(default='', max_length=40000)),
                ('metadata', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_msg_id', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-ts'],
            },
        ),
    ]
